---
title: "BOMBV DT Updated"
output: html_notebook
---





```{r}
BOMBVimp<-df7[, c('BOMBV','RESTm','LLOV','Village', 'BDBV','MLAV',
'Pig')]
```
```{r}
library(caret)
```
```{r}
#Create train/test split 70/30
set.seed(1234)
train <- sample(nrow(BOMBVimp), 0.7*nrow(BOMBVimp), replace = FALSE)
TrainSet <- BOMBVimp[train,]
ValidSet <- BOMBVimp[-train,]
summary(TrainSet)
summary(ValidSet)
TrainingParameters <- trainControl(method = "repeatedcv", number = 10, repeats=10,
                                   classProbs = TRUE,
                                   summaryFunction=twoClassSummary)
```
```{r}
library(DMwR)

## Smote : Synthetic Minority Oversampling Technique To Handle Class Imbalance In Binary Classification; code below puts it at 1:1 balance
balanced.data <- SMOTE(BOMBV ~., TrainSet, perc.over = 100)

as.data.frame(table(balanced.data$BOMBV))
```


```{r}
set.seed(1234)
library(caret)

```



```{r}

set.seed(1234)

# Train a model with above parameters. We will use rpart algorithm
DecTreeModel <- train(BOMBV ~ ., data = TrainSet, 
                      method = "rpart2",
                      tuneLength=6,
                      trControl= TrainingParameters,
                      metric="ROC")
                  
```
```{r}
DecTreeModel
```

```{r}
#Predictions
DTPredictions <-predict(DecTreeModel, ValidSet, na.action = na.pass)
# Print confusion matrix and results
cmTree <-confusionMatrix(DTPredictions, ValidSet$BOMBV,positive='Positive')
```

```{r}
cmTree
```

```{r}
library(pROC)
#Calculate ROC curve
rocCurve.dt<- roc(ValidSet$BOMBV,as.numeric(DTPredictions))
```

```{r}
#plot the ROC curve
plot(rocCurve.dt,col=c(1))
```

```{r}
auc(rocCurve.dt)
```

